---
title: How to BETTER learn English（私の良いと思う方法）
date: 2019-01-20 15:24:30
updated: 2020-06-20 16:43:30
categories:
- [HowTo]
tags:
- 英語学習
---


== この記事の目的
これまで、色々な人に自分の英語能力を驚かれることがあったので、意外と自分のやってきた英語学習方法が役に立つかもしれないと思ったのでまとめてみる。
これまでもまとめようと思ってはいたものの先延ばしにしていたところ、ちょうど会社のBossから教えてと言われたので、まとめてみます！参考になれば幸いです。

== Executive Summary
* 英語の勉強はシャドーイングが総合的に効果的！
* 基礎固めにはDuoがおすすめ。

== 前提　
=== 私について
英語は言葉なので能力を表現するのは難しいですが、事実を並べるとこんな感じです

* TOEIC 970 (Listening: 495, Reading: 475) as of 2011-09-11
** これ以降は受けたことないです（今は下がってるかも？）
* 学生時代、自分のCS分野研究を英語で論文＋国際学会発表などもやった
* 恐らく、海外の大学・大学院レベルのCS授業はついていける（はず）
** Online Course何個かやって修了しているので。
* 英語で仕事はできた
** フィリピンの人達とJavaの開発ができています
* 海外旅行に行っても、英語に関して大きな不自由は無い。友達ができて楽しい
* 帰国子女でも無い。海外生活も留学経験も無し。

決して、英語ネイティブレベルではありませんが、Non-nativeとして英語を使って色々できるレベルです。

=== 英語学習に関する個人的な考え
==== 英語学習以前に大事なこと
英語学習に関して、*_真実_* だと思うこと

* モチベーションが何より大事
** 効率的な勉強方法を知っていたとしても、継続しないと道半ばになる
** 継続するには身の回りの誘惑に勝つためのモチベーションが大事。
*** 僕の場合は、高校生の夏休みに参加した国籍MIXのサマーキャンプ。そこで英語が通じる楽しさを知って、もっとスキルを高めたいと思ったこと。コンピュータの勉強を初めて、CSはアメリカ主導であり、ほとんどの情報一次ソースが英語であるため、英語が出来ないとリアルに困る状況にいた事。
*** モチベーションは、個々人の状況に応じて、高めていくことが大切
*** 長期的には、健康にもいいらしい
**** https://courrier.jp/news/archives/72372/[バイリンガルはボケないし、1500万円も多く稼ぐ？ | 複数言語学習は脳に効く！（後編） | クーリエ・ジャポン]
* 魔法は無い(There is no magic)
** 地道な努力が必要、 ただしショートカットするための *_効率的なやり方_* は存在する（これを紹介していく）

==== 本記事で紹介する学習法について
* 英語スキルを高めると思われる方法を紹介します。
** TOEICの点数を高めることが主目的ではないです（ただ、必然的に高まります。テスト対策という意味ではもっといい方法があるかもしれません）

==== 英語学習の原則（と思う）
* 脳の上位機能を鍛えるべし：自分が喋れれば聞ける、書ければ読める
** Speaking ⊃ Listening
** Writing ⊃ Reading

* 教材について
** 構成: 音声とそのスクリプトがあれば、ある意味、なんでも良い
*** 音声: ネイティブスピード以上のもの（遅いものはいらない）。好みの発音があれば、それを選ぶ（アメリカ英語がいいとか、ブリティッシュが好きとか）
*** スクリプト: 日本語訳や、単語の意味が一緒に乗ってると、調べる手間が省けるのでベター
** コンテンツ: 後述

== マイルストーン
大きな考え方として、「1. 基礎固めフェーズ」→「2. 実践フェーズ」に分割できると思う。

* 「2. 実践フェーズ」 はいわば、”英語を使って”何かしらのコンテンツを学ぶことができるフェーズ +
英語が学ぶことが主目的であったとしても、英語をツールとしてそのコンテンツを学ぶというサブ目的が発生するフェーズである。英語スキルが高まるにつれて、*英語を学ぶこと自体* の目的度合いが下がり、*コンテンツを学ぶこと* の目的度合いが高まっていく。個人的にこのフェーズはだんだん楽しさが増していく。
* 「1. 基礎固めフェーズ」は、2.のフェーズで動き回れるためのエントリークライテリア +
基礎が確立していない状態で、2.に突入したり、いきなり英会話スクールに通ったりすると、”何が分からないのか”も分からない状態に陥りやすく効率が悪い。誰かが手取り足取り教えてくれるわけではないので、”分からないことが何か分かり”、”分からないこと”の量が多くなりすぎないことが大事（時間効率とモチベーション維持の意味で）。

あくまでも個人的な目安だが、TOEIC 730点くらいを達成すれば、「1. 基礎固めフェーズ」を卒業しても良いと思う。

* DUOの本のまえがきあたりに、そんなことを書いていた気がする
* TOEICのスコアとその評価目安によると730は1つのマイルストーンっぽい
** https://www.iibc-global.org/library/default/toeic/official_data/lr/pdf/proficiency.pdf[PROFICIENCY SCALE]


....
何かを学習するときによくある過ち
何かを学習するときによくある過ちが、実践フェーズに入るタイミングが早すぎることと、遅すぎること。
実践フェーズには、学習対象を使い始められる状態になって入ることが望ましいがこのタイミングが難しい。
遅すぎると準備しすぎて無駄な時間を過ごしてしまう。私は「準備しすぎ」タイプ。。

この本の「学び方を学ぶ」もオススメ 
https://amzn.to/2RR0Zq3[SOFT SKILLS　ソフトウェア開発者の人生マニュアル]
....

=== 1. 基礎固めフェーズ：TOEIC730点くらいまでを目指す人向け
教材はDUOが良い。他の教材に浮気せず、この１冊を自分にインストールする。
本の中のShort Sentence集に、効率よく重要な単語/熟語が散りばめられているので、時間効率が良い。

==== 教材
* 本体

++++
<a target="_blank"  href="https://www.amazon.co.jp/gp/product/4900790052/ref=as_li_tl?ie=UTF8&camp=247&creative=1211&creativeASIN=4900790052&linkCode=as2&tag=suke1031-22&linkId=c07a8c775d0a4e5dc6546f354c48b3fb"><img border="0" src="//ws-fe.amazon-adsystem.com/widgets/q?_encoding=UTF8&MarketPlace=JP&ASIN=4900790052&ServiceVersion=20070822&ID=AsinImage&WS=1&Format=_SL250_&tag=suke1031-22" ></a><img src="//ir-jp.amazon-adsystem.com/e/ir?t=suke1031-22&l=am2&o=9&a=4900790052" width="1" height="1" border="0" alt="" style="border:none !important; margin:0px !important;" />
++++

* 復習用CD: #これが重要#

++++
<a target="_blank"  href="https://www.amazon.co.jp/gp/product/4900790079/ref=as_li_tl?ie=UTF8&camp=247&creative=1211&creativeASIN=4900790079&linkCode=as2&tag=suke1031-22&linkId=6583bdff56e5fb82b4f61568f5fe5cb6"><img border="0" src="//ws-fe.amazon-adsystem.com/widgets/q?_encoding=UTF8&MarketPlace=JP&ASIN=4900790079&ServiceVersion=20070822&ID=AsinImage&WS=1&Format=_SL250_&tag=suke1031-22" ></a><img src="//ir-jp.amazon-adsystem.com/e/ir?t=suke1031-22&l=am2&o=9&a=4900790079" width="1" height="1" border="0" alt="" style="border:none !important; margin:0px !important;" />
++++

==== おすすめの勉強方法
コンセプトとしては、本を何周もして定着をさせる。

===== 1. 例文の意味内在化
最初のステップとして、まずは、例文を見て意味を把握できる状態になることが目標。

.1週目
* 例文を見て意味を把握する
** 単語の意味はすぐ書いているのでそれを見て理解する（詳しい説明がたくさん書いているが見ない）
** 例文を見ると同時に音声を聞いて、音読する。
* 例文全体として見て意味が分かるようになったら次の例文へ。
* 例えば、1日3セクションなど決めて、1週目はできるだけ早く終えると良い。
* 忘却曲線を意識して、昨日・一昨日分を本日分に加え、さらに追加復習すると効果的。

.2周目
* はっきりいって1週目の内容は忘れているが、気にしない
* やることは1週目と同じ。ただし、もっと早く進める（なぜなら1度やっているので）
* とにかく、例文を見て意味を把握できるか？がポイント。

上記は机に向かってやる作業だが、それ以外の電車に乗ってる間やお風呂に入っている間などの空き時間に音声を聞くと良い。

===== 2. シャドーイング
これで、意味が内在化されたため、「文字を読めば分かるという状態」になったはず。
次のステップは、聞いても「分かるという状態」（Listening）になり、さらに、その内容を喋れる状態になること（Speaking）。さらに、この過程を通して、さらに意味理解の定着を進め、「読めば分かる」度合いも深化させていく（Reading）。これを達成するのに有効な方法が *シャドーイング* である。

具体的な方法は以下の通り。各ステップを十分にこなせるまでは、次のステップに進んではならない。Duoの場合は、Section単位で下記を実践する。

. マンブリング 
** 音声を聞きながらぶつぶつ喋る。英語の意味を理解する必要はなく、音を意識してついていく。
** あまり上手く出来ないはずです（上手く出来たら、コンテンツが易しすぎる証拠）
. パラレル・リーディング
** テキストを見ながら、音声についていく。
** 音と文字をリンクさせる。
. シャドーイング
** もうテキストは見ない。聞こえてくる音声にひたすらついていく。
*** できるまで何度も繰り返す。初めてのコンテンツに対しては絶対できないが、必ずできるようになるので、諦めないでできるまで繰り返す。
** まずは、音についていけるようになり、次に意味も理解しながらついていけるように進む。
*** 聞こえてくる音声の音に注目する: 音やリズムを真似る。
*** 聞こえてくる音声の意味に注目する: 内容も理解しながらシャドーイングする。
*** もし分からないところがあれば、そこのスクリプト、単語の意味などを必要に応じて確認するを繰り返す
** もっと負荷をかけたいときは、音声の再生を早くする（e.g. 1.5倍速）
** 机に向かう以外の空き時間にも音声を聞きながらシャドーイングすると良い。
*** 電車の中でシャドーイングすると怪しいので、口パクパクぐらいでw

===== 3. 暗唱（レシテーション）
最終ステップは、暗唱(レシテーション)である。特別何かをするというわけではなく、学習結果としてこうなる可能性が高い。
ここまで来ると、完全暗唱まではいかないかもしれないが、音声の各例文の頭単語を聞くと、続きの例文が口から出てくる状態に近くなる。

* Duoのコンテンツはあなたに完全にインストールされた状態。
* 空き時間に音声を聞いてさらに反復する。
** シャドーイングをちゃんとやっていれば、”分からないこと”は発生しない

=== 2. 実践フェーズ：英語で何かを学べる、楽しいパート

==== 使用する教材のコンテンツについて
語学はツールなので、勉強しながら何か学べるのが良い。先にも書いたが、英語以外の学び部分の占める割合が増えてきたら、しめたもので、楽しくなってくる。とにかく、音声＋スクリプトがあれば何でも良いです。

* オススメのコンテンツ
** 僕が英語修行をしていたときは、CNNニュースのスクリプトを使っていました +
*** http://ee.asahipress.com/[CNN ENGLISH EXPRESS | 朝日出版社]
*** 1つ1つの長さがニュース単位で、音声が1~2分程度で短くちょうどいい。
*** 音声がアナウンサーのプロ英語話者なのでキレイな発音・トーンであるため、はじめのうちはオススメ。
*** 欠点はニュースの内容を学ぶ　というのがあまりモチベーション高まらないかも？（少なくとも私の場合は）
** TEDのプレゼン
*** 面白いコンテンツがたくさんあるし、プレゼンの練習にもなる。スクリプトがダウンロードできる。
*** https://www.ted.com/#/[TED: Ideas worth spreading]
** 好きなビジネス書のaudio book
** Podcast
*** https://www.allearsenglish.com/episodes/[Episodes | All Ears English Podcast]
**** 英語のいろんな表現（カジュアルなもの含めて）を教えてくれる。 
**** 有料で、Transcriptがダウンロードできる。
*** https://bilingualnews.libsyn.com/[バイリンガルニュース (Bilingual News)]
**** 世界の面白いニュースと、それについての語りが面白い
**** 有料で、Transcriptがダウンロードできる。

==== 学習方法
先に書いた「シャドーイング」の方法と同じやり方。
それに加えて、さらに負荷を高めたい場合や、他の技能を高めたい場合は、シャドーイングの後に下記のようなステップを付け加える。

* ディレイド・シャドーイング 
** 音を聞いてから1秒程度空けてから、シャドーイングする。
** オプショナルステップ。脳のワーキングメモリにもっと負荷を掛けたいときに
** 一度聞いた音声を脳の中に蓄えておくのは、会話中に割り込まれて聞こえた内容を蓄えていて、あとで反応するといったシチュエーションに近い気がする。
* リピーティング
** 聞いている音声を文単位で止めて、それを復唱するトレーニング。
* リード・アンド・ルックアップ
** テキストを文単位で読み、その文を声に出して読むトレーニング。
* ディクテーション
** 聞いている音声/読んでいるテキストを文単位で止めて、それを書き出すトレーニング。
*** ペンで書くとかタイピングする
** Writingの訓練になる

=== シャドーイングの効果について
下記文献に書いています。

* https://englishhub.jp/sla/shadowing-listening[第二言語習得から考える、なぜシャドーイングがリスニング力向上に効果的なのか？ | おすすめ英会話・英語学習の比較・ランキング- English Hub]
* この本が詳しい。大学1年生のとき、英語修行する前にあたった本。
https://amzn.to/2UmJivs[シャドーイングと音読の科学]
* http://www.tom-waras.com/book-1.html[「シャドーイングと音読の科学」という本を読んでみました]


ポイントは、シャドーイングによって、

* 音声知覚の自動化
* 脳の意味データベースの音声トリガー検索の自動化
* 発話による運動パートの訓練

がされること。
なので、リスニング力向上だけでなく、スピーキング力の向上も期待できます。

また、副次的に、シャドーイングによる訓練対象の教材がスクリプトを持っているので、それ自体が文章であり、その中で見つけた知らない単語やフレーズが意味データベースに追加されるため、

* 脳の意味データベースの更新

も行われるため、リーディング力やライティング力向上も期待できます。

== その後の英語学習
ここまで来ると、英語をツールとして何かをすることができるようになってくると思います。
そうすると、英語を学習する意識は薄れていって、副次的に英語スキルが向上していくということになリマス。
これまでのシャドーイング学習だけではカバーできない領域を意識すると良いかもしれません。
そして、実際に実践するというのが目的達成の基本的な方法となるはずです。

例えば、私の場合は下記のような領域を伸ばしていきたい

* ライティング
** e.g. 仕事で使えるテクニカル/ビジネスな/伝わる/効果的な　英文を書けるようになること。
* リーディング
** e.g. 難易度の高い長い文章を良いスピードで読みこなせること
* スピーキング
** e.g. ビジネスで喋ることの流暢さを増すこと、表現の幅を増やすこと
* リスニング
** e.g. 色々なバックグラウンドの人の英語を聞き取れること（non-native English speakerのほうが多いので）。インド英語とかはまだまだ苦手。。

=== Phrasal Verbs + Idiomsの重要性について
* Phrasal Verbsとは、look into みたいな、動詞+前置詞or副詞なもの。
* Idiomsは、piece of cakeみたいな、単語の並びで意味をなす語の集合で、構成する単語からは意味を推測できないし、その言語特有の表現になる。
https://blog.knudge.me/difference-between-idioms-and-phrasal-verbs-a8b8f8f92af7[DIFFERENCE BETWEEN IDIOMS AND PHRASAL VERBS - Knudge.me]


== その他便利ツール
* 英語勉強用ツール	https://note.mu/__shinji__/n/n528fafe9a8da
** マウスオーバーで超高速に辞書を引けるのが超便利　Mouse Dictionary (chrome addon)

* The Elements of Style	http://www.kt.rim.or.jp/~hisashim/elementsofstyle/elementsofstyle.html#intro		・英語文法の良いルール集

== Useful Resources
* 単語力増強
** https://www.english-corpora.org/coca/[Corpus of Contemporary American English (COCA)]
** iKnow
** Anki App

=== Writing
* ライティングして、クラウドの力で訂正してくれるコミュニティ型サービス
** https://lang-8.com/[Home | Lang-8: For learning foreign languages]
* 英語でブログを書く

=== Listening
* https://jp.quora.com/%E8%8B%B1%E8%AA%9E%E3%81%AE%E3%83%AA%E3%82%B9%E3%83%8B%E3%83%B3%E3%82%B0%E5%8A%9B%E3%82%92-%E7%9F%AD%E6%9C%9F%E9%96%93%E3%81%A7%E9%AB%98%E3%82%81%E3%82%8B%E6%96%B9%E6%B3%95%E3%81%AF%E3%81%82%E3%82%8A%E3%81%BE/answers/180341086?ch=99&share=f277f17a&srid=S05mS[英語のリスニング力を、短期間で高める方法はありますか？に対する武田 裕煕 (Yuki Takeda)さんの回答 - Quora]

....
下記ステップを1日1本の動画（10分程度）に対して実行する
1. 字幕付き・1.0x倍速で見て、内容を把握する。知らない単語は単語帳に登録する
2. 字幕なし・0.75x倍速で見て、聞き取れないところを虱潰しにする
わからなかったところは、単語単位でわかるまで繰り返し聞きましょう
どうしてもわからなければ字幕をオンにして確認しても大丈夫です。
3. 字幕なし・1.0x倍速で見て、普通の速度に慣れる
....